version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: stawwkom        # из вашего local.env
      POSTGRES_PASSWORD: pyborder28$ # из вашего local.env
      POSTGRES_DB: note             # из вашего local.env
    ports:
      - "54321:5432"                # из вашего local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
